### PR TITLE
Disable autoLiquidity, change LP, add withdrawEth function

### PR DESCRIPTION
**Pull request by meetmangukiya**
- Allow disabling autoLiquidity
- LP should be the smart contract, not 0x0
- Add `withdrawEth` function to only allow owners to withdraw funds

### CODE REVIEW

**Comment by meetmangukiya** [comment]
@cakebank can you review? Let me know if any changes needed

**Comment by cakebank** [comment]
> @cakebank can you review? Let me know if any changes needed

Let me check

**Comment by cakebank** [comment]
Hi, i check your code on the line

function withdrawEth(address payable to, uint256 amt) external onlyOwner {
require(address(this).balance >= amt);
to.transfer(amt);
}

If there is bnb and other token in the smart contract, do we able to withdraw all?

can we set a const for "LP" so it will be able to change , just like marketingFee, liquidityFee.

like if i change the LP token owner to be the smart contract itself, is it okay? then I can use withdrawEth to withdraw the LP Token and BNB, and other tokens? is that possible.

**Comment by cakebank** [comment]
> @cakebank i think we can do that, however, do you have some fixed tokens that you wish to transfer whose addresses we can code into the contract, we should be able to transfer like we are transfering `CAKE`
> https://github.com/cakebank/cakebank_sol/blob/02d531984d567b74ba8d6856e309f03058321a6f/CAKEBANK.sol#L375
> 
> 
> but for that we are going to need the address of the token contract like we have it here in the contract
> https://github.com/cakebank/cakebank_sol/blob/02d531984d567b74ba8d6856e309f03058321a6f/CAKEBANK.sol#L32
> 
> 
> other solution is we make the token contract address as an input, but you will always to provide it in that case instead of saying `CAKE`

yes

Can we like do the following that we can add and remove to the withdrawList by insert the token address

add and remove function for the "withdrawList" 

Initial value in arrayList is CAKE & BNB token

**Comment by meetmangukiya** [comment]
@cakebank added three methods:
- `setTokenAddress` to set BEP20, ERC20 token contract addresses
- `withdrawEth` to withdraw the chain native coin, ETH in case of ethereum blockchain, BNB in case of Binance Smart Chain, etc.
- `withdrawToken` to withdraw the ERC20, BEP20, etc. tokens, this method will use the token contract address set previously with `setTokenAddress` to call the token contract.

**Comment by cakebank** [comment]
> @cakebank added three methods:
> 
> * `setTokenAddress` to set BEP20, ERC20 token contract addresses
> * `withdrawEth` to withdraw the chain native coin, ETH in case of ethereum blockchain, BNB in case of Binance Smart Chain, etc.
> * `withdrawToken` to withdraw the ERC20, BEP20, etc. tokens, this method will use the token contract address set previously with `setTokenAddress` to call the token contract.

May I check with you if the following is accomplished.


1. Disable autoLiquidity
2. Change LP Token Owner (The contract got an autoLiquidity function, current owner is 0x000000, I would like to able to change via BSCSCAN "writeCode" to  maybe this smart contract as the owner, so he will have the LP Token.
3. Withdraw BNB & BEP20 Token in the smart contract.

Is all okay? Thanks

**Comment by meetmangukiya** [comment]
Yes,
1. Disable autoliquidity - if liquidityFee is set to 0, we wont liquify https://github.com/cakebank/cakebank_sol/blob/1381fd0c14d8b67ab2490b5be2e52e9d05dd66f5/CAKEBANK.sol#L351-L354
2. "The smart contract" is the LP receiver, changed from 0 https://github.com/cakebank/cakebank_sol/blob/1381fd0c14d8b67ab2490b5be2e52e9d05dd66f5/CAKEBANK.sol#L481
3. Withdraw BNB and BEP20 tokens with these 2 functions: https://github.com/cakebank/cakebank_sol/blob/1381fd0c14d8b67ab2490b5be2e52e9d05dd66f5/CAKEBANK.sol#L202-L222

**Comment by meetmangukiya** [comment]
@cakebank ~thanks for merging, can you approve on gitcoin?~
whoops sorry, seems like bounty is paid, approval is pending?

**Pull request merged**
